Update package.json
The remark/rehype updates change the minimum required node version to 18. Not sure if that is then also needed for this package. 

This resolves the following error for me:
```
TypeError: Failed to parse Markdown file "/Users/matho180/nf-core.astro/src/content/about/about.md":
Cannot read properties of undefined (reading 'inTable')
    at Object.exitCodeText (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
    at compile (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
    at fromMarkdown (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
    at parser (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/remark-parse/lib/index.js:18:12)
    at Function.parse (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:273:12)
    at executor (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:380:14)
    at Object.render (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/dist/index.js:89:35)
    at Object.load (file:///Users/matho180/nf-core.astro/node_modules/astro/dist/vite-plugin-markdown/index.js:62:46)
```